version: '3.8'
services:
  vcc-app:
    build: .
    ports:
      - "5173:5173"  # Vite
      - "3000:3000"  # API
      - "8080:8080"  # ABS RPC
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - XERO_CLIENT_ID=${XERO_CLIENT_ID}
      - XERO_CLIENT_SECRET=${XERO_CLIENT_SECRET}
      - ABS_API_KEY=${ABS_API_KEY}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-vcc_australia}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
