version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - XERO_CLIENT_ID=${XERO_CLIENT_ID}
      - XERO_CLIENT_SECRET=${XERO_CLIENT_SECRET}
      - ABS_API_KEY=${ABS_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - SENTRY_DSN=${SENTRY_DSN}
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    mem_swappiness: 0
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-0-dogok4o8oo484440cogcckgk.entryPoints=http"
      - "traefik.http.routers.http-0-dogok4o8oo484440cogcckgk.middlewares=gzip"
      - "traefik.http.routers.http-0-dogok4o8oo484440cogcckgk.rule=Host(`vcc.myinvoices.today`) && PathPrefix(`/`)"
      - "traefik.http.routers.http-0-dogok4o8oo484440cogcckgk.service=http-0-dogok4o8oo484440cogcckgk"
      - "traefik.http.services.http-0-dogok4o8oo484440cogcckgk.loadbalancer.server.port=3000"
    restart: unless-stopped
