http:
  routers:
    vcc-router:
      rule: "Host(`vcc.myinvoices.today`)"
      service: vcc-service
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    vcc-service:
      loadBalancer:
        servers:
          - url: "http://vcc-abs-staging:3000"
